language: python
python:
    - "2.7"
before_script:
    - cd EXOSIMS/util/KeplerSTM_C/
    - python CyKeplerSTM_setup.py build_ext --inplace
    - cd ../../..
script:
    coverage run -m unittest discover -v
after_success:
    coveralls

